services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"               # host:container
    environment:
      - SERVER_PORT=5000          # app.listen usa 5000
      - DB_HOST=db
      - DB_USER=dev
      - DB_PASSWORD=1234
      - DB_NAME=wagerdb
      - SECRET_KEY=4567
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"   # << aqui o ajuste
    restart: always

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    restart: always

  db:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wagerdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
